sql.subscriptions.select.all = SELECT * FROM fn_get_subscriptions()
sql.subscription.add = {call sp_add_subscription(?, ?, ?)}
sql.subscription.delete = {call sp_delete_subscription(?)}

sql.label.select.all = SELECT * FROM fn_get_labels()
sql.label.add = {call sp_add_label(?, ?)}
sql.label.delete = {call sp_delete_label(?)}
sql.label.update = {call sp_update_label(?, ?, ?)}

sql.artist.select.all = SELECT * FROM fn_get_artists()
sql.artist.add = {call sp_add_artist(?, ?, ?)}
sql.artist.update =  {call sp_update_artist(?, ?, ?, ?)}
sql.artist.delete = {call sp_delete_artist(?)}